# Generated by Django 3.1.4 on 2020-12-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='homepage')),
            ],
            options={
                'verbose_name_plural': 'index',
            },
        ),
        migrations.CreateModel(
            name='myprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='profile')),
            ],
            options={
                'verbose_name_plural': 'myprofile',
            },
        ),
        migrations.CreateModel(
            name='myservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('Fittings', 'Fittings'), ('Wiring', 'Wiring'), ('Tiles', 'Tiles'), ('Ceilings', 'Ceilings'), ('Plumbing', 'Plumbing'), ('Painting', 'Painting')], max_length=15)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='services')),
            ],
            options={
                'verbose_name_plural': 'myservices',
            },
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('img', models.ImageField(upload_to='homepage')),
            ],
            options={
                'verbose_name_plural': 'slider',
            },
        ),
        migrations.CreateModel(
            name='workexperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='myworkexperience')),
            ],
            options={
                'verbose_name_plural': 'workexperience',
            },
        ),
    ]
