# Generated by Django 3.1.4 on 2020-12-16 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myadvert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myservices',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 16, 13, 5, 21, 886045, tzinfo=utc)),
        ),
    ]
